name: Monitor DANDI Compute

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  CheckEngaging:
    name: Pre-run Check
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v6

      - name: Cancel if offline
        uses: ./.github/actions/check-runner
        with:
          org: CodyCBakerPhD/self-hosted-crons
          labels: mit,engaging,monitor
          token: ${{ secrets._GITHUB_API_KEY }}

  MonitorDANDICompute:
    needs: CheckEngaging
    name: Monitor DANDI Compute
    runs-on: [self-hosted, mit, engaging, monitor]
    timeout-minutes: 2880  # 2 days, same as mit_preemtable

    steps:
      - name: Checkout repository
        run: |
          while true; do
            echo "Timestamp: $(date)"
            squeue --format="%.10i %15P %40j %10u %.2t %.10M %.6D %.2C %30R" --me
            sleep 300
          done

  NotifyOnFailure:
    if: ${{ always() && failure() }}  # 'always' for if any 'needs' are cancelled/skipped
    needs: [CheckEngaging, MonitorDANDICompute]
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification on failure
        uses: dawidd6/action-send-mail@v17
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Monitor DANDI Compute failed (MIT Engaging)"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: Typhon CRON
          body: |
            The scheduled run of DANDI Compute monitoring workflow encountered an issue, please check status at
            https://github.com/CodyCBakerPhD/self-hosted-crons/actions/workflows/name-monitor+dandi+compute_trigger-cron+dispatch_freq-12+hours
