name: Sync GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '55 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

jobs:
  CheckEngaging:
    name: Pre-run Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cancel if offline
        uses: ./.github/actions/check-runner
        with:
          org: CodyCBakerPhD/self-hosted-crons
          labels: mit,engaging,compute
          token: ${{ secrets._GITHUB_API_KEY }}

  RunAINDEphys:
    needs: CheckEngaging
    name: Run AIND Ephys
    runs-on: [self-hosted, mit, engaging, compute]

    steps:
      - name: Update whole Dandiset copy
        working-directory: /orcd/data/dandi/001/dandi-compute/dandi
        run: dandi download DANDI:001697 --sync --existing skip

      - name: Sync with GitHub and push
        working-directory: /orcd/data/dandi/001/dandi-compute
        run: |
          git -C github/001697 fetch --all
          git -C github/001697 reset --hard origin/main

          rsync -a --delete --exclude='.git' --exclude='.datalad' --exclude='README.md' dandi/001697/ github/001697/
          find github/001697/ -name '*.nwb' -type f -delete  # TODO: until proper DataLad with annexed NWBs to special remote

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git -C github/001697 add .
          git -C github/001697 commit --message "update" || true  # || true in case of no changes
          git -C github/001697 push

  NotifyOnFailure:
    if: ${{ always() && failure() }}  # 'always' for if any 'needs' are cancelled/skipped
    needs: [CheckEngaging, RunAINDEphys]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check 24-hour cooldown
        id: cooldown
        uses: ./.github/actions/check-cooldown
        with:
          workflow_file: sync_github.yml
          token: ${{ github.token }}

      - name: Send email notification on failure
        if: ${{ steps.cooldown.outputs.should_notify == 'true' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "DANDI Compute: DANDI <-> GitHub Sync of 001697 failed"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: Typhon CRON
          body: |
            The scheduled run of DANDI <-> GitHub Sync of 001697 encountered an issue!
            Please check status at: https://github.com/dandi-compute/submitter/actions/workflows/sync_github.yml
