name: Sync DataLad

on:
  workflow_dispatch:
  schedule:
    - cron: '55 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
  GITHUB_TOKEN: ${{ secrets._GITHUB_API_KEY }}

jobs:
  CheckEngaging:
    name: Pre-run Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cancel if offline
        uses: ./.github/actions/check-runner
        with:
          org: CodyCBakerPhD/self-hosted-crons
          labels: mit,engaging,compute
          token: ${{ secrets._GITHUB_API_KEY }}

  RunAINDEphys:
    needs: CheckEngaging
    name: Run AIND Ephys
    runs-on: [self-hosted, mit, engaging, compute]

    steps:
      - name: Update DataLad dataset
        working-directory: /orcd/data/dandi/001/dandi-compute
        run: |
          git config --global datalad.credential.api.github.com.token "${GITHUB_TOKEN}"

          backups2datalad --backup-root ./datalad/ --config ./datalad/config.yaml update-from-backup 001697

      - name: Push to GitHub
        working-directory: /orcd/data/dandi/001/dandi-compute
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git -C ./datalad/dandisets/001697 remote set-url github https://x-access-token:${GITHUB_TOKEN}@github.com/dandi-compute/001697.git
          git -C ./datalad/dandisets/001697 remote set-url --push github https://x-access-token:${GITHUB_TOKEN}@github.com/dandi-compute/001697.git

          cd ./datalad/dandisets/001697
          #datalad push --to github

  NotifyOnFailure:
    if: ${{ always() && failure() }}  # 'always' for if any 'needs' are cancelled/skipped
    needs: [CheckEngaging, RunAINDEphys]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check 24-hour cooldown
        id: cooldown
        uses: ./.github/actions/check-cooldown
        with:
          workflow_file: sync_datalad.yml
          token: ${{ github.token }}

      - name: Send email notification on failure
        if: ${{ steps.cooldown.outputs.should_notify == 'true' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "DANDI Compute: DANDI <-> GitHub Sync of 001697 failed"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: Typhon CRON
          body: |
            The scheduled run of DANDI <-> DataLad GitHub Sync of 001697 encountered an issue!
            Please check status at: https://github.com/dandi-compute/submitter/actions/workflows/sync_datalad.yml
